name             'dobc'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apachev2'
issues_url       'https://github.com/osuosl-cookbooks/dobc/issues'
source_url       'https://github.com/osuosl-cookbooks/dobc'
description      'Installs/Configures dobc'
long_description 'Installs/Configures dobc'
version          '0.1.0'

supports         'centos', '~> 7.0'
